[2024-12-29T15:26:12.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-29T15:26:12.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T15:26:11.329336+00:00 [queued]>
[2024-12-29T15:26:12.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T15:26:11.329336+00:00 [queued]>
[2024-12-29T15:26:12.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-29T15:26:12.385+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2024-12-29 15:26:11.329336+00:00
[2024-12-29T15:26:12.394+0000] {standard_task_runner.py:63} INFO - Started process 1140 to run task
[2024-12-29T15:26:12.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2024-12-29T15:26:11.329336+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmp466vdlp_']
[2024-12-29T15:26:12.415+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask extract.extract_and_load_to_staging
[2024-12-29T15:26:12.562+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T15:26:11.329336+00:00 [running]> on host 52712ca165cb
[2024-12-29T15:26:12.819+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T15:26:11.329336+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T15:26:11.329336+00:00'
[2024-12-29T15:26:12.823+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-29T15:26:13.743+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T15:26:13.865+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T15:26:13.982+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-12-29T15:26:14.014+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-29T15:26:14.024+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2018, in execute
    cur.execute(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1046, 'No database selected')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 263, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 564, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2078, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2030, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM product_category_name_translation': (1046, 'No database selected')
[2024-12-29T15:26:14.429+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2024-12-29T15:26:11.329336+00:00, execution_date=20241229T152611, start_date=20241229T152612, end_date=20241229T152614
[2024-12-29T15:26:14.562+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task extract.extract_and_load_to_staging (Execution failed on sql 'SELECT * FROM product_category_name_translation': (1046, 'No database selected'); 1140)
[2024-12-29T15:26:14.624+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-29T15:26:14.708+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-29T15:26:14.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
