[2025-01-07T15:13:52.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T15:13:52.177+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.is_accurate scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-07T15:13:52.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.is_accurate scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-07T15:13:52.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-07T15:13:52.210+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): is_accurate> on 2025-01-06 00:00:00+00:00
[2025-01-07T15:13:52.215+0000] {standard_task_runner.py:63} INFO - Started process 3082 to run task
[2025-01-07T15:13:52.219+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'is_accurate', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '878', '--raw', '--subdir', 'DAGS_FOLDER/das_ytb.py', '--cfg-path', '/tmp/tmpvf3ulrv4']
[2025-01-07T15:13:52.222+0000] {standard_task_runner.py:91} INFO - Job 878: Subtask is_accurate
[2025-01-07T15:13:52.270+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.is_accurate scheduled__2025-01-06T00:00:00+00:00 [running]> on host 4ff5b0867c78
[2025-01-07T15:13:52.512+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='is_accurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-07T15:13:52.513+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T15:13:52.524+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-07T15:13:52.525+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'accurate'"]
[2025-01-07T15:13:52.535+0000] {subprocess.py:86} INFO - Output:
[2025-01-07T15:13:52.537+0000] {subprocess.py:93} INFO - accurate
[2025-01-07T15:13:52.538+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-07T15:13:52.540+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T15:13:52.571+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=is_accurate, run_id=scheduled__2025-01-06T00:00:00+00:00, execution_date=20250106T000000, start_date=20250107T151352, end_date=20250107T151352
[2025-01-07T15:13:52.633+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-07T15:13:52.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T15:13:52.657+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
